apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pre-sync.yaml
- canary-rollout.yaml
- canary-service.yaml
- canary-ingress.yaml
- canary-preview-service.yaml
- canary-preview-ingress.yaml
- analysis-success-rate.yaml
